# Common Tensor Operations

In [2]:
import torch

### `.reshape()` & `.view()`

So far, we went over 
1. How to create a tensor using `torch.tensor()`
2. How to see the dimensions of a tensor with `.shape`

Another common operation is the `.reshape()` operation, which literally, reshapes a tensor into the dimension you want.

In [3]:
before_reshape = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(f"Before reshape: {before_reshape}")
print(f"shape: {before_reshape.shape}")

Before reshape: tensor([[1, 2, 3],
        [4, 5, 6]])
shape: torch.Size([2, 3])


In [4]:
after_reshape = before_reshape.reshape(3, 2)
print(f"After reshape: {after_reshape}")
print(f"shape: {after_reshape.shape}")

After reshape: tensor([[1, 2],
        [3, 4],
        [5, 6]])
shape: torch.Size([3, 2])


The only restriction with the `.reshape()` method is that the number of elements in the tensors need to match. 

In [5]:
before_reshape.size()

torch.Size([2, 3])

Since the `before_reshape` tensor has `2 * 3 = 6` numbers, the pair of numbers that go into `.reshape()` needs to equal `6` when they are multiplied. 

The `view` operation essentially does the same thing: 

In [6]:
tensor2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor2d, tensor2d.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

In [8]:
tensor2d.view(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

### Transpose with `.T`

To transpose a tensor, you can use `.T`

In [9]:
before_t = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(f"Before transpose: {before_t}")
print(f"shape: {before_t.shape}")

Before transpose: tensor([[1, 2, 3],
        [4, 5, 6]])
shape: torch.Size([2, 3])


In [10]:
after_t = before_t.T
print(f"After transpose: {after_t}")
print(f"shape: {after_t.shape}")

After transpose: tensor([[1, 4],
        [2, 5],
        [3, 6]])
shape: torch.Size([3, 2])


Note that transposing a tensor yields a different result from reshaping it. 

In [11]:
tensor2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
reshaped_tensor = tensor2d.reshape(3, 2)
transposed_tensor = tensor2d.T
print(f"Reshaped tensor:\n{reshaped_tensor}\n")
print(f"Transposed tensor:\n{transposed_tensor}")

Reshaped tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])

Transposed tensor:
tensor([[1, 4],
        [2, 5],
        [3, 6]])


## Matrix Multiplication with `matmul()`

The `.matmul()` operation enables matrix multiplication. 

In [17]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.T
print(f"t1:\n{t1}\n")
print(f"t2:\n{t2}\n")


t1:
tensor([[1, 2, 3],
        [4, 5, 6]])

t2:
tensor([[1, 4],
        [2, 5],
        [3, 6]])



In [18]:
res_matmul = t1.matmul(t2)
print(f"Result of matmul:\n{res_matmul}\n")
print(f"Shape of result: {res_matmul.shape}\n")

Result of matmul:
tensor([[14, 32],
        [32, 77]])

Shape of result: torch.Size([2, 2])



The shape of the matrix multiplication is as expected: `[2 x 3]` * `[3 x 2]` = `[2 x 2]`