# PyTorch Tensor Basics

Install PyTorch and Torchvision

In [2]:
!pip3 install torch torchvision -Uq


In [3]:
import torch

Check if compatible with Apple Silicon

In [6]:
is_mchip_compatible = torch.backends.mps.is_available()
print(f"Is PyTorch compatible with Apple Silicon M1/M2 chip? {is_mchip_compatible}")

Is PyTorch compatible with Apple Silicon M1/M2 chip? True


A tensor is a representation of a 0-dimensional, 1-dimensional, or multi-dimensional array of numbers. 0-dimensional tensors can be referred to as *scalars*, which simply means the tensor is a singular number. 

A scalar in PyTorch can be initialized by passing in a single integer or float to `torch.tensor`. You can check the zero-dimensionality by checking the `shape` attribute of the tensor, which will tell you the dimensions of the tensor. 

In [ ]:
scalar = torch.tensor(1)
scalar, scalar.shape

(tensor(1), torch.Size([]))

Here's an example of a 1D tensor, which will just look like a list of numbers.

In [10]:
tensor_1d = torch.tensor([1, 2, 3])
tensor_1d, tensor_1d.shape


(tensor([1, 2, 3]), torch.Size([3]))

You'll notice that the 1D tensor's shape is `[3]`, which you can think of as 1 row, 3 columns, with the `1` part excluded. 1D tensors are referred to as *vectors*. 

In [11]:
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor_2d, tensor_2d.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

Looking above at a 2D tensor -- also called a *matrix* -- the `shape` attribute shows that the tensor has 2 "rows" and 3 "columns". 

At this point it becomes clear that:
1. displaying the tensor itself shows the tensor & its contents
2. displaying the `shape` of the tensor shows how many "rows" and "columns" your tensor has

There aren't specific terms for tensors that go beyond 3D, so it's safe to say we can refer to them as multi-dimensional tensors, or `n`D-tensors, with `n` being whatever dimension the tensor is. 

In [12]:
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
tensor_3d, tensor_3d.shape

(tensor([[[1, 2],
          [3, 4]],
 
         [[5, 6],
          [7, 8]]]),
 torch.Size([2, 2, 2]))